runtime: go119

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
  # - url: /assets(.*\.svg)
  #   mime_type: image/svg+xml
  #   static_files: dist/assets/\1
  #   upload: dist/assets/(.*\.svg)
  #   expiration: "7d"

  # - url: /assets(.*\.js)
  #   mime_type: "text/javascript; charset: utf-8"
  #   static_files: dist/assets/\1
  #   upload: dist/assets/(.*\.js)
  #   expiration: "7d"

  # - url: /assets(.*\.css)
  #   mime_type: "text/css; charset: utf-8"
  #   static_files: dist/assets/\1
  #   upload: dist/assets/(.*\.css)
  #   expiration: "7d"

  - url: /.*
    script: auto
    secure: always